import { Character } from './types';

export const tw: Character[] = [
  { _id: 'alencia', name: '艾蓮西雅', rarity: 5, role: 'Warrior', attribute: 'Earth', zodiac: 'Cancer' },
  {
    _id: 'ambitious-tywin',
    name: '野心份子泰溫',
    rarity: 5,
    role: 'Knight',
    attribute: 'Light',
    zodiac: 'Sagittarius',
  },
  {
    _id: 'apocalypse-ravi',
    name: '末日蘿菲',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Cancer',
  },
  { _id: 'aramintha', name: '雅拉敏塔', rarity: 5, role: 'Mage', attribute: 'Fire', zodiac: 'Gemini' },
  {
    _id: 'arbiter-vildred',
    name: '執行官維德瑞',
    rarity: 5,
    role: 'Thief',
    attribute: 'Dark',
    zodiac: 'Leo',
  },
  {
    _id: 'archdemons-shadow',
    name: '魔神的暗影',
    rarity: 5,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Aquarius',
  },
  { _id: 'baal-sezan', name: '巴爾＆塞尚', rarity: 5, role: 'Mage', attribute: 'Fire', zodiac: 'Gemini' },
  { _id: 'baiken', name: '梅喧', rarity: 5, role: 'Thief', attribute: 'Earth', zodiac: 'Scorpio' },
  { _id: 'basar', name: '巴薩爾', rarity: 5, role: 'Mage', attribute: 'Earth', zodiac: 'Aquarius' },
  { _id: 'bellona', name: '維爾蘿娜', rarity: 5, role: 'Ranger', attribute: 'Earth', zodiac: 'Capricorn' },
  {
    _id: 'blood-moon-haste',
    name: '赤月貴族海斯特',
    rarity: 5,
    role: 'Soul Weaver',
    attribute: 'Dark',
    zodiac: 'Pisces',
  },
  {
    _id: 'bomb-model-kanna',
    name: '暴擊型卡農',
    rarity: 5,
    role: 'Ranger',
    attribute: 'Fire',
    zodiac: 'Gemini',
  },
  {
    _id: 'briar-witch-iseria',
    name: '\u7070\u5149\u68ee\u6797\u7684\u4f0a\u8cfd\u9e97\u4e9e',
    rarity: 5,
    role: 'Ranger',
    attribute: 'Dark',
    zodiac: 'Gemini',
  },
  { _id: 'cecilia', name: '\u8cfd\u897f\u8389\u4e9e', rarity: 5, role: 'Knight', attribute: 'Fire', zodiac: 'Aries' },
  { _id: 'celine', name: '\u745f\u7433', rarity: 5, role: 'Thief', attribute: 'Earth', zodiac: 'Scorpio' },
  { _id: 'cerise', name: '\u8cfd\u745e\u7d72', rarity: 5, role: 'Ranger', attribute: 'Ice', zodiac: 'Aquarius' },
  { _id: 'cermia', name: '\u6f54\u82e5\u7c73\u4e9e', rarity: 5, role: 'Warrior', attribute: 'Fire', zodiac: 'Leo' },
  { _id: 'charles', name: '\u67e5\u723e\u65af', rarity: 5, role: 'Knight', attribute: 'Earth', zodiac: 'Gemini' },
  { _id: 'charlotte', name: '\u590f\u7da0\u8482', rarity: 5, role: 'Knight', attribute: 'Fire', zodiac: 'Leo' },
  { _id: 'chloe', name: '\u514b\u863f\u611b', rarity: 5, role: 'Warrior', attribute: 'Ice', zodiac: 'Sagittarius' },
  { _id: 'choux', name: '\u5c0f\u6ce1\u8299', rarity: 5, role: 'Warrior', attribute: 'Ice', zodiac: 'Capricorn' },
  {
    _id: 'dark-corvus',
    name: '\u9ed1\u6697\u7684\u79d1\u723e\u5e03\u601d',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Capricorn',
  },
  {
    _id: 'desert-jewel-basar',
    name: '\u6c99\u6f20\u5bf6\u77f3\u5df4\u85a9\u723e',
    rarity: 5,
    role: 'Soul Weaver',
    attribute: 'Light',
    zodiac: 'Sagittarius',
  },
  {
    _id: 'designer-lilibet',
    name: '\u8a2d\u8a08\u5e2b\u8389\u8389\u8c9d',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Cancer',
  },
  { _id: 'destina', name: '\u6234\u7d72\u8482\u5a1c', rarity: 5, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Cancer' },
  { _id: 'diene', name: '\u8fea\u57c3\u59ae', rarity: 5, role: 'Soul Weaver', attribute: 'Ice', zodiac: 'Gemini' },
  { _id: 'dizzy', name: '\u8482\u59ec', rarity: 5, role: 'Mage', attribute: 'Ice', zodiac: 'Taurus' },
  { _id: 'eda', name: '\u827e\u59b2', rarity: 5, role: 'Mage', attribute: 'Ice', zodiac: 'Aries' },
  { _id: 'elena', name: '\u827e\u857e\u5a1c', rarity: 5, role: 'Soul Weaver', attribute: 'Ice', zodiac: 'Gemini' },
  { _id: 'elphelt', name: '\u611b\u723e\u83f2\u7279', rarity: 5, role: 'Ranger', attribute: 'Fire', zodiac: 'Capricorn' },
  {
    _id: 'ervalen',
    name: '\u827e\u723e\u5df4\u502b',
    rarity: 5,
    role: 'Thief',
    attribute: 'Earth',
    zodiac: 'Scorpio',
  },
  {
    _id: 'fairytale-tenebria',
    name: '\u7ae5\u8a71\u6cf0\u59ae\u5e03\u91cc\u96c5',
    rarity: 5,
    role: 'Mage',
    attribute: 'Ice',
    zodiac: 'Taurus',
  },
  {
    _id: 'faithless-lidica',
    name: '\u7121\u795e\u8ad6\u8005\u9e97\u8fea\u5361',
    rarity: 5,
    role: 'Ranger',
    attribute: 'Light',
    zodiac: 'Gemini',
  },
  {
    _id: 'fallen-cecilia',
    name: '\u58ae\u843d\u7684\u8cfd\u897f\u8389\u4e9e',
    rarity: 5,
    role: 'Knight',
    attribute: 'Dark',
    zodiac: 'Sagittarius',
  },
  { _id: 'flan', name: '\u8299\u862d', rarity: 5, role: 'Ranger', attribute: 'Ice', zodiac: 'Capricorn' },
  { _id: 'haste', name: '\u6d77\u65af\u7279', rarity: 5, role: 'Thief', attribute: 'Fire', zodiac: 'Gemini' },
  {
    _id: 'holiday-yufine',
    name: '\u5ea6\u5047\u98a8\u512a\u82ac\u59ae',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Fire',
    zodiac: 'Libra',
  },
  { _id: 'iseria', name: '\u4f0a\u8cfd\u9e97\u4e9e', rarity: 5, role: 'Ranger', attribute: 'Earth', zodiac: 'Leo' },
  {
    _id: 'judge-kise',
    name: '\u5be9\u5224\u8005\u7dba\u4e16',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Light',
    zodiac: 'Virgo',
  },
  { _id: 'kawerik', name: '\u5361\u5a01\u5229', rarity: 5, role: 'Mage', attribute: 'Fire', zodiac: 'Virgo' },
  { _id: 'kayron', name: '\u51f1\u9686', rarity: 5, role: 'Thief', attribute: 'Fire', zodiac: 'Aries' },
  { _id: 'ken', name: '\u80af\u6069', rarity: 5, role: 'Warrior', attribute: 'Fire', zodiac: 'Capricorn' },
  { _id: 'kise', name: '\u7dba\u4e16', rarity: 5, role: 'Thief', attribute: 'Ice', zodiac: 'Leo' },
  { _id: 'krau', name: '\u514b\u52de\u70cf', rarity: 5, role: 'Knight', attribute: 'Ice', zodiac: 'Pisces' },
  { _id: 'landy', name: '\u862d\u8482', rarity: 5, role: 'Ranger', attribute: 'Earth', zodiac: 'Leo' },
  {
    _id: 'last-rider-krau',
    name: '\u6700\u5f8c\u7684\u9a0e\u58eb\u514b\u52de\u70cf',
    rarity: 5,
    role: 'Knight',
    attribute: 'Light',
    zodiac: 'Pisces',
  },
  { _id: 'lidica', name: '\u9e97\u8fea\u5361', rarity: 5, role: 'Ranger', attribute: 'Fire', zodiac: 'Virgo' },
  { _id: 'lilias', name: '\u8389\u8389\u4e9e\u65af', rarity: 5, role: 'Knight', attribute: 'Fire', zodiac: 'Aries' },
  { _id: 'lilibet', name: '\u8389\u8389\u8c9d', rarity: 5, role: 'Warrior', attribute: 'Earth', zodiac: 'Libra' },
  {
    _id: 'little-queen-charlotte',
    name: '\u5e74\u8f15\u7684\u5973\u738b\u590f\u7da0\u8482',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Light',
    zodiac: 'Libra',
  },
  { _id: 'ludwig', name: '\u9b6f\u7279\u6bd4', rarity: 5, role: 'Mage', attribute: 'Earth', zodiac: 'Leo' },
  { _id: 'luluca', name: '\u7490\u7490\u5361', rarity: 5, role: 'Mage', attribute: 'Ice', zodiac: 'Aquarius' },
  { _id: 'luna', name: '\u9732\u5a1c', rarity: 5, role: 'Warrior', attribute: 'Ice', zodiac: 'Libra' },
  {
    _id: 'maid-chloe',
    name: '\u50d5\u4eba\u514b\u863f\u611b',
    rarity: 5,
    role: 'Soul Weaver',
    attribute: 'Light',
    zodiac: 'Virgo',
  },
  {
    _id: 'martial-artist-ken',
    name: '\u6b66\u9b25\u5bb6\u80af\u6069',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Leo',
  },
  {
    _id: 'mediator-kawerik',
    name: '\u5354\u8abf\u8005\u5361\u5a01\u5229',
    rarity: 5,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Capricorn',
  },
  { _id: 'melissa', name: '\u6885\u9e97\u838e', rarity: 5, role: 'Mage', attribute: 'Fire', zodiac: 'Leo' },
  { _id: 'mort', name: '\u9b54\u52d2', rarity: 5, role: 'Knight', attribute: 'Earth', zodiac: 'Gemini' },
  { _id: 'mui', name: '\u7e46\u4f0a', rarity: 5, role: 'Warrior', attribute: 'Earth', zodiac: 'Virgo' },
  {
    _id: 'operator-sigret',
    name: '\u64cd\u4f5c\u54e1\u8cfd\u73c2\u862d\u7279',
    rarity: 5,
    role: 'Ranger',
    attribute: 'Dark',
    zodiac: 'Libra',
  },
  { _id: 'pavel', name: '\u5e15\u8c9d\u723e', rarity: 5, role: 'Ranger', attribute: 'Earth', zodiac: 'Virgo' },
  { _id: 'politis', name: '\u4f5b\u91cc\u8482\u7d72', rarity: 5, role: 'Mage', attribute: 'Fire', zodiac: 'Gemini' },
  { _id: 'ravi', name: '\u863f\u83f2', rarity: 5, role: 'Warrior', attribute: 'Fire', zodiac: 'Capricorn' },
  { _id: 'ray', name: '\u96f7\u4f0a', rarity: 5, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Taurus' },
  {
    _id: 'remnant-violet',
    name: '\u6b98\u5f71\u7684\u83f2\u5967\u96f7\u6258',
    rarity: 5,
    role: 'Thief',
    attribute: 'Dark',
    zodiac: 'Leo',
  },
  { _id: 'roana', name: '\u7f85\u5b89\u7d0d', rarity: 5, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Pisces' },
  {
    _id: 'ruele-of-light',
    name: '\u5149\u4e4b\u745e\u5152',
    rarity: 5,
    role: 'Soul Weaver',
    attribute: 'Light',
    zodiac: 'Pisces',
  },
  {
    _id: 'sage-baal-sezan',
    name: '\u8ce2\u8005\u5df4\u723e&\u585e\u5c1a',
    rarity: 5,
    role: 'Mage',
    attribute: 'Light',
    zodiac: 'Taurus',
  },
  {
    _id: 'seaside-bellona',
    name: '\u6d77\u908a\u7684\u7dad\u723e\u863f\u5a1c',
    rarity: 5,
    role: 'Ranger',
    attribute: 'Ice',
    zodiac: 'Gemini',
  },
  { _id: 'senya', name: '\u8cfd\u5a1c', rarity: 5, role: 'Knight', attribute: 'Earth', zodiac: 'Taurus' },
  { _id: 'sez', name: '\u8cfd\u8332', rarity: 5, role: 'Thief', attribute: 'Ice', zodiac: 'Scorpio' },
  { _id: 'sigret', name: '\u8cfd\u73c2\u862d\u7279', rarity: 5, role: 'Warrior', attribute: 'Ice', zodiac: 'Taurus' },
  {
    _id: 'silver-blade-aramintha',
    name: '\u767d\u9280\u5200\u5203\u7684\u96c5\u62c9\u654f\u5854',
    rarity: 5,
    role: 'Mage',
    attribute: 'Light',
    zodiac: 'Gemini',
  },
  { _id: 'sol', name: '\u7d22\u723e', rarity: 5, role: 'Warrior', attribute: 'Fire', zodiac: 'Sagittarius' },
  {
    _id: 'solitaria-of-the-snow',
    name: '\u96ea\u570b\u7684\u8607\u8389\u5854\u59ae\u4e9e',
    rarity: 5,
    role: 'Mage',
    attribute: 'Light',
    zodiac: 'Taurus',
  },
  {
    _id: 'specimen-sez',
    name: '\u5be6\u9a57\u9ad4\u8cfd\u8332',
    rarity: 5,
    role: 'Thief',
    attribute: 'Light',
    zodiac: 'Scorpio',
  },
  {
    _id: 'specter-tenebria',
    name: '\u5e7b\u5f71\u7684\u6cf0\u59ae\u5e03\u91cc\u96c5',
    rarity: 5,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Gemini',
  },
  {
    _id: 'tamarinne',
    name: '\u5854\u746a\u6797\u723e',
    rarity: 5,
    role: 'Soul Weaver',
    attribute: 'Fire',
    zodiac: 'Sagittarius',
  },
  {
    _id: 'tenebria',
    name: '\u6cf0\u59ae\u5e03\u91cc\u96c5',
    rarity: 5,
    role: 'Mage',
    attribute: 'Fire',
    zodiac: 'Cancer',
  },
  {
    _id: 'top-model-luluca',
    name: '\u6700\u5f37\u6a21\u7279\u5152\u7490\u7490\u5361',
    rarity: 5,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Sagittarius',
  },
  { _id: 'tywin', name: '\u6cf0\u6eab', rarity: 5, role: 'Knight', attribute: 'Ice', zodiac: 'Aries' },
  { _id: 'vildred', name: '\u7dad\u5fb7\u745e', rarity: 5, role: 'Thief', attribute: 'Earth', zodiac: 'Leo' },
  {
    _id: 'violet',
    name: '\u83f2\u5967\u96f7\u6258',
    rarity: 5,
    role: 'Thief',
    attribute: 'Earth',
    zodiac: 'Scorpio',
  },
  { _id: 'vivian', name: '\u8587\u8587\u5b89', rarity: 5, role: 'Mage', attribute: 'Earth', zodiac: 'Sagittarius' },
  { _id: 'yufine', name: '\u512a\u82ac\u59ae', rarity: 5, role: 'Warrior', attribute: 'Earth', zodiac: 'Taurus' },
  { _id: 'yuna', name: '\u5c24\u5a1c', rarity: 5, role: 'Ranger', attribute: 'Ice', zodiac: 'Leo' },
  { _id: 'zeno', name: '\u5091\u8afe', rarity: 5, role: 'Mage', attribute: 'Ice', zodiac: 'Taurus' },
  { _id: 'achates', name: '\u96c5\u5361\u6cf0\u7d72', rarity: 4, role: 'Soul Weaver', attribute: 'Fire', zodiac: 'Gemini' },
  { _id: 'angelica', name: '\u5b89\u6f54\u8389\u5361', rarity: 4, role: 'Soul Weaver', attribute: 'Ice', zodiac: 'Cancer' },
  { _id: 'armin', name: '\u4e9e\u654f', rarity: 4, role: 'Knight', attribute: 'Earth', zodiac: 'Capricorn' },
  {
    _id: 'assassin-cartuja',
    name: '\u6bba\u624b\u5361\u723e\u5716\u54c8',
    rarity: 4,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Scorpio',
  },
  {
    _id: 'assassin-cidd',
    name: '\u6bba\u624b\u5e2d\u5fb7',
    rarity: 4,
    role: 'Thief',
    attribute: 'Dark',
    zodiac: 'Aquarius',
  },
  {
    _id: 'assassin-coli',
    name: '\u6bba\u624b\u53ef\u9e97',
    rarity: 4,
    role: 'Thief',
    attribute: 'Dark',
    zodiac: 'Taurus',
  },
  {
    _id: 'auxiliary-lots',
    name: '\u8f14\u52a9\u578b\u62c9\u8332',
    rarity: 4,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Pisces',
  },
  {
    _id: 'benevolent-romann',
    name: '\u4ec1\u6148\u7684\u6d1b\u66fc',
    rarity: 4,
    role: 'Mage',
    attribute: 'Light',
    zodiac: 'Taurus',
  },
  {
    _id: 'blaze-dingo',
    name: '\u70c8\u706b\u6c40\u679c',
    rarity: 4,
    role: 'Soul Weaver',
    attribute: 'Light',
    zodiac: 'Sagittarius',
  },
  {
    _id: 'blood-blade-karin',
    name: '\u8840\u528d\u5361\u7433',
    rarity: 4,
    role: 'Thief',
    attribute: 'Dark',
    zodiac: 'Scorpio',
  },
  { _id: 'cartuja', name: '\u5361\u723e\u5716\u54c8', rarity: 4, role: 'Warrior', attribute: 'Earth', zodiac: 'Cancer' },
  {
    _id: 'celestial-mercedes',
    name: '\u5916\u592a\u7a7a\u7684\u73ab\u52d2\u8cfd\u5fb7\u7d72',
    rarity: 4,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Scorpio',
  },
  {
    _id: 'challenger-dominiel',
    name: '\u6311\u6230\u8005\u591a\u7c73\u59ae\u723e',
    rarity: 4,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Scorpio',
  },
  {
    _id: 'champion-zerato',
    name: '\u7d42\u7d50\u8005\u6770\u62c9\u5716',
    rarity: 4,
    role: 'Mage',
    attribute: 'Dark',
    zodiac: 'Aries',
  },
  { _id: 'cidd', name: '\u5e2d\u5fb7', rarity: 4, role: 'Thief', attribute: 'Earth', zodiac: 'Aries' },
  { _id: 'clarissa', name: '\u514b\u840a\u8389\u838e', rarity: 4, role: 'Warrior', attribute: 'Ice', zodiac: 'Leo' },
  { _id: 'coli', name: '\u53ef\u9e97', rarity: 4, role: 'Thief', attribute: 'Ice', zodiac: 'Scorpio' },
  { _id: 'corvus', name: '\u79d1\u723e\u5e03\u601d', rarity: 4, role: 'Warrior', attribute: 'Fire', zodiac: 'Cancer' },
  {
    _id: 'crescent-moon-rin',
    name: '\u65b0\u6708\u821e\u59ec\u9234\u5152',
    rarity: 4,
    role: 'Thief',
    attribute: 'Dark',
    zodiac: 'Taurus',
  },
  {
    _id: 'crimson-armin',
    name: '\u7d05\u7130\u4e9e\u654f',
    rarity: 4,
    role: 'Knight',
    attribute: 'Light',
    zodiac: 'Libra',
  },
  { _id: 'crozet', name: '\u514b\u7f85\u6fa4', rarity: 4, role: 'Knight', attribute: 'Ice', zodiac: 'Cancer' },
  { _id: 'dingo', name: '\u6c40\u679c', rarity: 4, role: 'Warrior', attribute: 'Fire', zodiac: 'Virgo' },
  { _id: 'dominiel', name: '\u591a\u7c73\u59ae\u723e', rarity: 4, role: 'Mage', attribute: 'Ice', zodiac: 'Taurus' },
  {
    _id: 'fighter-maya',
    name: '\u6230\u9b25\u578b\u746a\u96c5',
    rarity: 4,
    role: 'Knight',
    attribute: 'Light',
    zodiac: 'Libra',
  },
  {
    _id: 'free-spirit-tieria',
    name: '\u6c38\u6046\u4e0d\u8b8a\u7684\u9edb\u8389\u4e9e',
    rarity: 4,
    role: 'Warrior',
    attribute: 'Light',
    zodiac: 'Virgo',
  },
  { _id: 'furious', name: '\u5c24\u8c9d\u70cf\u65af', rarity: 4, role: 'Ranger', attribute: 'Ice', zodiac: 'Leo' },
  {
    _id: 'general-purrgis',
    name: '\u5927\u5c07\u6cd5\u6fdf\u65af',
    rarity: 4,
    role: 'Warrior',
    attribute: 'Light',
    zodiac: 'Cancer',
  },
  {
    _id: 'great-chief-khawana',
    name: '\u5927\u65cf\u9577\u5361\u74e6\u5a1c',
    rarity: 4,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Taurus',
  },
  {
    _id: 'guider-aither',
    name: '\u6c42\u9053\u8005\u57c3\u5fb7\u52d2',
    rarity: 4,
    role: 'Mage',
    attribute: 'Light',
    zodiac: 'Cancer',
  },
  { _id: 'karin', name: '\u5361\u7433', rarity: 4, role: 'Thief', attribute: 'Ice', zodiac: 'Leo' },
  { _id: 'khawana', name: '\u5361\u74e6\u5a1c', rarity: 4, role: 'Thief', attribute: 'Fire', zodiac: 'Pisces' },
  { _id: 'khawazu', name: '\u5361\u74e6\u6731', rarity: 4, role: 'Warrior', attribute: 'Fire', zodiac: 'Scorpio' },
  {
    _id: 'kitty-clarissa',
    name: '\u8c93\u54aa\u514b\u840a\u8389\u838e',
    rarity: 4,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Virgo',
  },
  { _id: 'kizuna-ai', name: '\u7d46\u611b', rarity: 4, role: 'Soul Weaver', attribute: 'Fire', zodiac: 'Cancer' },
  { _id: 'leo', name: '\u96f7\u6b50', rarity: 4, role: 'Ranger', attribute: 'Earth', zodiac: 'Capricorn' },
  { _id: 'lots', name: '\u62c9\u8332', rarity: 4, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Gemini' },
  { _id: 'maya', name: '\u746a\u96c5', rarity: 4, role: 'Knight', attribute: 'Fire', zodiac: 'Aries' },
  {
    _id: 'mercedes',
    name: '\u73ab\u52d2\u8cfd\u5fb7\u7d72',
    rarity: 4,
    role: 'Mage',
    attribute: 'Fire',
    zodiac: 'Scorpio',
  },
  { _id: 'purrgis', name: '\u6cd5\u6fdf\u65af', rarity: 4, role: 'Warrior', attribute: 'Earth', zodiac: 'Scorpio' },
  { _id: 'rin', name: '\u9234\u5152', rarity: 4, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Virgo' },
  {
    _id: 'roaming-warrior-leo',
    name: '\u6d41\u6d6a\u52c7\u58eb\u96f7\u6b50',
    rarity: 4,
    role: 'Ranger',
    attribute: 'Dark',
    zodiac: 'Gemini',
  },
  { _id: 'romann', name: '\u6d1b\u66fc', rarity: 4, role: 'Mage', attribute: 'Ice', zodiac: 'Gemini' },
  { _id: 'rose', name: '\u863f\u5b63', rarity: 4, role: 'Knight', attribute: 'Ice', zodiac: 'Libra' },
  { _id: 'schuri', name: '\u4fee\u91cc', rarity: 4, role: 'Ranger', attribute: 'Fire', zodiac: 'Leo' },
  { _id: 'serila', name: '\u585e\u9e97\u62c9', rarity: 4, role: 'Mage', attribute: 'Fire', zodiac: 'Aquarius' },
  {
    _id: 'shadow-rose',
    name: '\u6697\u5f71\u863f\u5b63',
    rarity: 4,
    role: 'Knight',
    attribute: 'Dark',
    zodiac: 'Gemini',
  },
  {
    _id: 'shooting-star-achates',
    name: '\u6d41\u661f\u96c5\u5361\u6cf0\u7d72',
    rarity: 4,
    role: 'Soul Weaver',
    attribute: 'Dark',
    zodiac: 'Cancer',
  },
  { _id: 'silk', name: '\u5e2d\u53ef', rarity: 4, role: 'Ranger', attribute: 'Earth', zodiac: 'Virgo' },
  {
    _id: 'sinful-angelica',
    name: '\u7f6a\u623e\u7684\u5b89\u6f54\u8389\u5361',
    rarity: 4,
    role: 'Soul Weaver',
    attribute: 'Dark',
    zodiac: 'Taurus',
  },
  { _id: 'surin', name: '\u8607\u7433', rarity: 4, role: 'Thief', attribute: 'Fire', zodiac: 'Gemini' },
  {
    _id: 'tempest-surin',
    name: '\u98a8\u96f2\u8607\u7433',
    rarity: 4,
    role: 'Thief',
    attribute: 'Light',
    zodiac: 'Gemini',
  },
  {
    _id: 'troublemaker-crozet',
    name: '\u4e0d\u6cd5\u4e4b\u5f92\u514b\u7f85\u6fa4',
    rarity: 4,
    role: 'Knight',
    attribute: 'Dark',
    zodiac: 'Pisces',
  },
  {
    _id: 'wanderer-silk',
    name: '\u6d41\u6d6a\u8005\u5e2d\u53ef',
    rarity: 4,
    role: 'Ranger',
    attribute: 'Light',
    zodiac: 'Capricorn',
  },
  {
    _id: 'watcher-schuri',
    name: '\u6ce8\u8996\u8005\u4fee\u91cc',
    rarity: 4,
    role: 'Ranger',
    attribute: 'Light',
    zodiac: 'Scorpio',
  },
  { _id: 'zerato', name: '\u6770\u62c9\u5716', rarity: 4, role: 'Mage', attribute: 'Ice', zodiac: 'Aries' },
  { _id: 'adlay', name: '\u4e9e\u8fea\u8cf4', rarity: 3, role: 'Mage', attribute: 'Earth', zodiac: 'Sagittarius' },
  {
    _id: 'adventurer-ras',
    name: '\u5192\u96aa\u5bb6\u62c9\u65af',
    rarity: 3,
    role: 'Knight',
    attribute: 'Fire',
    zodiac: 'Libra',
  },
  { _id: 'ainos', name: '\u827e\u8afe\u65af', rarity: 3, role: 'Soul Weaver', attribute: 'Dark', zodiac: 'Sagittarius' },
  { _id: 'ains', name: '\u827e\u56e0\u8332', rarity: 3, role: 'Warrior', attribute: 'Earth', zodiac: 'Libra' },
  { _id: 'aither', name: '\u57c3\u5fb7\u52d2', rarity: 3, role: 'Soul Weaver', attribute: 'Ice', zodiac: 'Libra' },
  { _id: 'alexa', name: '\u96c5\u8389\u838e', rarity: 3, role: 'Thief', attribute: 'Ice', zodiac: 'Leo' },
  {
    _id: 'allrounder-wanda',
    name: '\u7591\u96e3\u96dc\u75c7\u5c08\u5bb6\u6c6a\u9054',
    rarity: 3,
    role: 'Ranger',
    attribute: 'Dark',
    zodiac: 'Gemini',
  },
  {
    _id: 'angelic-montmorancy',
    name: '\u5b88\u8b77\u5929\u4f7f\u8499\u8309\u6717\u897f',
    rarity: 3,
    role: 'Soul Weaver',
    attribute: 'Ice',
    zodiac: 'Pisces',
  },
  { _id: 'arowell', name: '\u96c5\u6d1b\u8587', rarity: 3, role: 'Knight', attribute: 'Light', zodiac: 'Libra' },
  {
    _id: 'azalea',
    name: '\u4e9e\u6f54\u7406\u4e9e',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Fire',
    zodiac: 'Scorpio',
  },
  { _id: 'bask', name: '\u5df4\u601d\u514b', rarity: 3, role: 'Knight', attribute: 'Ice', zodiac: 'Scorpio' },
  { _id: 'batisse', name: '\u5df4\u6258\u65af', rarity: 3, role: 'Warrior', attribute: 'Dark', zodiac: 'Taurus' },
  {
    _id: 'butcher-corps-inquisitor',
    name: '\u5c60\u6bba\u90e8\u968a\u54e1',
    rarity: 3,
    role: 'Knight',
    attribute: 'Fire',
    zodiac: 'Leo',
  },
  {
    _id: 'captain-rikoris',
    name: '\u5148\u92d2\u968a\u9577\u91cc\u79d1\u9ece\u53f8',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Light',
    zodiac: 'Libra',
  },
  {
    _id: 'carmainerose',
    name: '\u5361\u9ea5\u863f\u8332',
    rarity: 3,
    role: 'Mage',
    attribute: 'Fire',
    zodiac: 'Aquarius',
  },
  { _id: 'carrot', name: '\u5361\u863f', rarity: 3, role: 'Mage', attribute: 'Fire', zodiac: 'Sagittarius' },
  { _id: 'celeste', name: '\u8cfd\u96f7\u65af\u7279', rarity: 3, role: 'Ranger', attribute: 'Light', zodiac: 'Sagittarius' },
  {
    _id: 'chaos-inquisitor',
    name: '\u6df7\u6c8c\u6559\u5c60\u6bba\u8ffd\u64ca\u8005',
    rarity: 3,
    role: 'Knight',
    attribute: 'Fire',
    zodiac: 'Leo',
  },
  {
    _id: 'chaos-sect-axe',
    name: '\u6df7\u6c8c\u6559\u5de8\u65a7\u5927\u5c07\u8ecd',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Leo',
  },
  {
    _id: 'church-of-ilryos-axe',
    name: '\u4f0a\u5229\u6b50\u65af\u6559\u65a7\u5175',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Leo',
  },
  {
    _id: 'commander-lorina',
    name: '\u6307\u63ee\u5b98\u863f\u91cc\u5a1c',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Dark',
    zodiac: 'Leo',
  },
  {
    _id: 'doll-maker-pearlhorizon',
    name: '\u88fd\u5076\u5e2b\u6ce2\u863f\u840a\u73cd',
    rarity: 3,
    role: 'Mage',
    attribute: 'Earth',
    zodiac: 'Taurus',
  },
  { _id: 'doris', name: '\u6735\u8389\u601d', rarity: 3, role: 'Soul Weaver', attribute: 'Light', zodiac: 'Cancer' },
  { _id: 'eaton', name: '\u4f0a\u9813', rarity: 3, role: 'Knight', attribute: 'Light', zodiac: 'Cancer' },
  { _id: 'elson', name: '\u827e\u723e\u68ee', rarity: 3, role: 'Soul Weaver', attribute: 'Light', zodiac: 'Pisces' },
  { _id: 'enott', name: '\u827e\u8afe\u7279', rarity: 3, role: 'Warrior', attribute: 'Ice', zodiac: 'Scorpio' },
  {
    _id: 'falconer-kluri',
    name: '\u9df9\u7375\u4eba\u53ef\u9732\u8389',
    rarity: 3,
    role: 'Knight',
    attribute: 'Earth',
    zodiac: 'Aries',
  },
  { _id: 'glenn', name: '\u683c\u502b', rarity: 3, role: 'Ranger', attribute: 'Earth', zodiac: 'Libra' },
  { _id: 'gloomyrain', name: '\u683c\u9b6f\u7f8e\u862d', rarity: 3, role: 'Mage', attribute: 'Light', zodiac: 'Cancer' },
  { _id: 'godmother', name: '\u6559\u6bcd', rarity: 3, role: 'Ranger', attribute: 'Fire', zodiac: 'Gemini' },
  { _id: 'gunther', name: '\u5764\u7279', rarity: 3, role: 'Warrior', attribute: 'Light', zodiac: 'Libra' },
  { _id: 'hataan', name: '\u54c8\u5766', rarity: 3, role: 'Thief', attribute: 'Fire', zodiac: 'Leo' },
  { _id: 'hazel', name: '\u6d77\u8332', rarity: 3, role: 'Soul Weaver', attribute: 'Fire', zodiac: 'Aquarius' },
  { _id: 'helga', name: '\u8d6b\u723e\u5609', rarity: 3, role: 'Warrior', attribute: 'Earth', zodiac: 'Sagittarius' },
  { _id: 'hurado', name: '\u4fee\u62c9\u675c', rarity: 3, role: 'Mage', attribute: 'Dark', zodiac: 'Pisces' },
  { _id: 'ian', name: '\u4f0a\u5b89', rarity: 3, role: 'Ranger', attribute: 'Ice', zodiac: 'Virgo' },
  { _id: 'jecht', name: '\u5091\u514b\u6258', rarity: 3, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Sagittarius' },
  { _id: 'jena', name: '\u6377\u5a1c', rarity: 3, role: 'Mage', attribute: 'Ice', zodiac: 'Aries' },
  { _id: 'judith', name: '\u8331\u8fea\u7d72', rarity: 3, role: 'Thief', attribute: 'Fire', zodiac: 'Pisces' },
  {
    _id: 'kikirat-v2',
    name: '\u5947\u5947\u62c9\u7279V.2',
    rarity: 3,
    role: 'Knight',
    attribute: 'Light',
    zodiac: 'Capricorn',
  },
  { _id: 'kiris', name: '\u5947\u9e97\u7d72', rarity: 3, role: 'Ranger', attribute: 'Earth', zodiac: 'Capricorn' },
  { _id: 'kluri', name: '\u53ef\u9732\u8389', rarity: 3, role: 'Knight', attribute: 'Earth', zodiac: 'Aries' },
  { _id: 'lena', name: '\u96f7\u5a1c', rarity: 3, role: 'Warrior', attribute: 'Ice', zodiac: 'Libra' },
  { _id: 'lorina', name: '\u863f\u91cc\u5a1c', rarity: 3, role: 'Warrior', attribute: 'Dark', zodiac: 'Leo' },
  { _id: 'lucy', name: '\u9732\u897f', rarity: 3, role: 'Soul Weaver', attribute: 'Earth', zodiac: 'Virgo' },
  {
    _id: 'magic-scholar-doris',
    name: '\u9b54\u6cd5\u5b78\u8005\u6735\u8389\u601d',
    rarity: 3,
    role: 'Soul Weaver',
    attribute: 'Light',
    zodiac: 'Cancer',
  },
  {
    _id: 'mascot-hazel',
    name: '\u5409\u7965\u7269\u6d77\u8332',
    rarity: 3,
    role: 'Soul Weaver',
    attribute: 'Fire',
    zodiac: 'Aquarius',
  },
  {
    _id: 'mercenary-helga',
    name: '\u81ea\u7531\u81ea\u5728\u7684\u50ad\u5175\u8d6b\u723e\u5609',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Earth',
    zodiac: 'Sagittarius',
  },
  { _id: 'mirsa', name: '\u7c73\u52d2\u838e', rarity: 3, role: 'Thief', attribute: 'Light', zodiac: 'Pisces' },
  { _id: 'mistychain', name: '\u7f8e\u7d72\u7df9\u5f69', rarity: 3, role: 'Mage', attribute: 'Ice', zodiac: 'Leo' },
  {
    _id: 'montmorancy',
    name: '\u8499\u8309\u6717\u897f',
    rarity: 3,
    role: 'Soul Weaver',
    attribute: 'Ice',
    zodiac: 'Pisces',
  },
  { _id: 'mucacha', name: '\u7a46\u5361\u5bdf', rarity: 3, role: 'Warrior', attribute: 'Earth', zodiac: 'Sagittarius' },
  {
    _id: 'muse-rima',
    name: '\u7e46\u65af\u9ece\u746a',
    rarity: 3,
    role: 'Ranger',
    attribute: 'Ice',
    zodiac: 'Aquarius',
  },
  { _id: 'nemunas', name: '\u5c3c\u59c6\u62c9\u65af', rarity: 3, role: 'Ranger', attribute: 'Fire', zodiac: 'Libra' },
  { _id: 'otillie', name: '\u5967\u7df9\u8389\u723e', rarity: 3, role: 'Mage', attribute: 'Dark', zodiac: 'Taurus' },
  { _id: 'pearlhorizon', name: '\u6ce2\u863f\u840a\u73cd', rarity: 3, role: 'Mage', attribute: 'Earth', zodiac: 'Taurus' },
  { _id: 'pyllis', name: '\u8cbb\u8389\u7d72', rarity: 3, role: 'Knight', attribute: 'Dark', zodiac: 'Cancer' },
  { _id: 'ras', name: '\u62c9\u65af', rarity: 3, role: 'Knight', attribute: 'Fire', zodiac: 'Libra' },
  {
    _id: 'requiemroar',
    name: '\u96f7\u594e\u59c6\u6d1b',
    rarity: 3,
    role: 'Soul Weaver',
    attribute: 'Dark',
    zodiac: 'Sagittarius',
  },
  {
    _id: 'researcher-carrot',
    name: '\u7814\u7a76\u8005\u5361\u863f',
    rarity: 3,
    role: 'Mage',
    attribute: 'Fire',
    zodiac: 'Sagittarius',
  },
  {
    _id: 'righteous-thief-roozid',
    name: '\u7fa9\u8cca\u9b6f\u8332\u5fb7',
    rarity: 3,
    role: 'Thief',
    attribute: 'Earth',
    zodiac: 'Gemini',
  },
  {
    _id: 'rikoris',
    name: '\u91cc\u79d1\u9ece\u53f8',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Light',
    zodiac: 'Libra',
  },
  { _id: 'rima', name: '\u9ece\u746a', rarity: 3, role: 'Ranger', attribute: 'Ice', zodiac: 'Aquarius' },
  { _id: 'roozid', name: '\u9b6f\u8332\u5fb7', rarity: 3, role: 'Thief', attribute: 'Earth', zodiac: 'Gemini' },
  { _id: 'sonia', name: '\u8607\u5c3c\u5a6d', rarity: 3, role: 'Soul Weaver', attribute: 'Light', zodiac: 'Pisces' },
  { _id: 'sven', name: '\u53f2\u8cd3', rarity: 3, role: 'Thief', attribute: 'Dark', zodiac: 'Scorpio' },
  {
    _id: 'taranor-guard',
    name: '\u5854\u62c9\u8afe\u723e\u7981\u885b\u968a\u54e1',
    rarity: 3,
    role: 'Warrior',
    attribute: 'Ice',
    zodiac: 'Libra',
  },
  {
    _id: 'taranor-royal-guard',
    name: '\u5854\u62c9\u8afe\u723e\u738b\u5bae\u58eb\u5175',
    rarity: 3,
    role: 'Knight',
    attribute: 'Ice',
    zodiac: 'Scorpio',
  },
  { _id: 'tieria', name: '\u9edb\u8389\u4e9e', rarity: 3, role: 'Warrior', attribute: 'Fire', zodiac: 'Aries' },
  { _id: 'wanda', name: '\u6c6a\u9054', rarity: 3, role: 'Ranger', attribute: 'Dark', zodiac: 'Gemini' },
  {
    _id: 'zealot-carmainerose',
    name: '\u50b3\u9053\u8005\u5361\u9ea5\u863f\u8332',
    rarity: 3,
    role: 'Mage',
    attribute: 'Fire',
    zodiac: 'Aquarius',
  },
];
